INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('15', 'Región de Arica y Parinacota', '1');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('1', 'Región de Tarapacá', '2');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('2', 'Región de Antofagasta', '3');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('3', 'Región de Atacama', '4');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('4', 'Región de Coquimbo', '5');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('5', 'Región de Valparaíso', '6');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('13', 'Región Metropolitana ', '7');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('6', 'Región de Ohiggins', '8');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('7', 'Región de Maule', '9');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('16', 'Región de Ñuble', '10');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('8', 'Región de Bio-Bio', '11');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('9', 'Región de Araucania', '12');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('14', 'Región de los Ríos', '13');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('10', 'Región de los Lagos', '14');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('11', 'Región de Aysen', '15');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('12', 'Región de Magallanes', '16');

INSERT INTO `comentarios`(`id`, `comentario`, `create_at`, `email`, `region_id`) VALUES (1,'Comentario 1','2022-04-05','rodrigo.navarro19@gmail.com',13);
INSERT INTO `comentarios`(`id`, `comentario`, `create_at`, `email`, `region_id`) VALUES (2,'Comentario 2','2022-04-05','correo2@gmail.com',12);
INSERT INTO `comentarios`(`id`, `comentario`, `create_at`, `email`, `region_id`) VALUES (3,'Comentario 3','2022-04-05','correo3@gmail.com',15);
INSERT INTO `comentarios`(`id`, `comentario`, `create_at`, `email`, `region_id`) VALUES (4,'Comentario 4','2022-04-05','correo4@gmail.com',5);
INSERT INTO `comentarios`(`id`, `comentario`, `create_at`, `email`, `region_id`) VALUES (5,'Comentario 5','2022-04-05','correo5@gmail.com',7);
INSERT INTO `comentarios`(`id`, `comentario`, `create_at`, `email`, `region_id`) VALUES (6,'Comentario 6','2022-04-05','correo6@gmail.com',6);
INSERT INTO `comentarios`(`id`, `comentario`, `create_at`, `email`, `region_id`) VALUES (7,'Comentario 7','2022-04-05','correo7@gmail.com',2);
INSERT INTO `comentarios`(`id`, `comentario`, `create_at`, `email`, `region_id`) VALUES (8,'Comentario 8','2022-04-05','correo8@gmail.com',9);
INSERT INTO `comentarios`(`id`, `comentario`, `create_at`, `email`, `region_id`) VALUES (9,'Comentario 9','2022-04-05','correo9@gmail.com',13);
INSERT INTO `comentarios`(`id`, `comentario`, `create_at`, `email`, `region_id`) VALUES (10,'Comentario 10','2022-04-05','correo10@gmail.com',13);
INSERT INTO `comentarios`(`id`, `comentario`, `create_at`, `email`, `region_id`) VALUES (11,'Comentario 10','2022-04-05','correo11@gmail.com',11);
INSERT INTO `comentarios`(`id`, `comentario`, `create_at`, `email`, `region_id`) VALUES (12,'Comentario 10','2022-04-05','correo12@gmail.com',10);
INSERT INTO `comentarios`(`id`, `comentario`, `create_at`, `email`, `region_id`) VALUES (13,'Comentario 10','2022-04-05','correo13@gmail.com',10);
INSERT INTO `comentarios`(`id`, `comentario`, `create_at`, `email`, `region_id`) VALUES (14,'Comentario 10','2022-04-05','correo14@gmail.com',3);
INSERT INTO `comentarios`(`id`, `comentario`, `create_at`, `email`, `region_id`) VALUES (15,'Comentario 10','2022-04-05','correo15@gmail.com',3);
