INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('15', 'Región de Arica y Parinacota', '1');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('1', 'Región de Tarapacá', '2');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('2', 'Región de Antofagasta', '3');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('3', 'Región de Atacama', '4');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('4', 'Región de Coquimbo', '5');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('5', 'Región de Valparaíso', '6');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('13', 'Región Metropolitana ', '7');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('6', 'Región de Ohiggins', '8');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('7', 'Región de Maule', '9');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('16', 'Región de Ñuble', '10');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('8', 'Región de Bio-Bio', '11');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('9', 'Región de Araucania', '12');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('14', 'Región de los Ríos', '13');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('10', 'Región de los Lagos', '14');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('11', 'Región de Aysen', '15');
INSERT INTO `regiones` (`id`, `nombre`, `orden`) VALUES ('12', 'Región de Magallanes', '16');